version: '3.3'

services:
   db:
     image: {{ mysql_image_name }}
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: {{ mysql_root_password }}
       MYSQL_DATABASE: {{ mysql_db }}
       MYSQL_USER: {{ mysql_user }}
       MYSQL_PASSWORD: {{ mysql_password }}

   wordpress:
     depends_on:
       - db
     image: {{ wordpress_image_name }}
     ports:
       - "{{ wordpress_base_port }}:{{ wordpress_container_port }}"
     restart: always
     environment:
       WORDPRESS_DB_HOST: {{ wordpress_db_host }}
       WORDPRESS_DB_USER: {{ mysql_user }}
       WORDPRESS_DB_PASSWORD: {{ mysql_password }}
volumes:
    dbdata:


